---
apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: tomcat-service
    labels:
      app: tomcat
      role: blue
      env: prod
  spec:
    type: LoadBalancer
    selector:
      app: tomcat
      role: blue
    ports:
      - port: 80
        targetPort: 8080
- kind: Service
  apiVersion: v1
  metadata:
    name: tomcat-test-blue
    labels:
      app: tomcat
      role: test-blue
  spec:
    type: LoadBalancer
    selector:
      app: tomcat
      role: blue
    ports:
      - port: 80
        targetPort: 8080
- kind: Service
  apiVersion: v1
  metadata:
    name: tomcat-test-green
    labels:
      app: tomcat
      role: test-green
  spec:
    type: LoadBalancer
    selector:
      app: tomcat
      role: green
    ports:
      - port: 80
        targetPort: 8080
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: tomcat-deployment-blue
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: tomcat
          role: blue
      spec:
        containers:
        - name: tomcat-container
          image: tomcat:7
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: tomcat-deployment-green
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: tomcat
          role: green
      spec:
        containers:
        - name: tomcat-container
          image: tomcat:7
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
